import { Roboto } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./components/AppContext";
import Header from "./components/layout/header";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased">
        <main className="max-w-8xl mx-auto p-4 bg-gray-900">
          <AppProvider>
          <Header />
        {children}

         <footer className="border-t mt-10 p-8 text-center text-gray-500">
        &copy; 2025 All rights reserved
      </footer>
      </AppProvider>
        </main>
      
      </body>
    </html>
  );
}
